title: Brandon Vo
logo: /assets/img/headshot_circle.png
description: Engineer experienced in domain of software, electronics, and electrical engineering.
show_downloads: true
theme: jekyll-theme-minimal
